### PR TITLE
fix admin route #78

### LINKED ISSUE #78: fix admin route (effort 3)
get all users:
filter out admins
remove email from path, instead add userId

remove email from each path and instead pass ids

change owner status:

image

check this error in each update function (in the app)

### PR DESCRIPTION
**Pull request by ibednorz**

### CODE REVIEW

File: services/adminService.js [hunk 1]
```diff
@@ -13,46 +15,78 @@ exports.getHotelOwners = async (role) => {
...
 }
 
-exports.acceptOwnersEmail = async (email, role) => {
-  const user = await User.updateOne({ email: email }, { role: role })
+exports.acceptUserToOwner = async (id, role) => {
+  const user = await User.updateOne({ _id: id }, { role: role })
 
   if (!user) {
-    throw new ApiError(404, 'User not found')
+    throw new ApiError(400, 'User not found')
```
Comment (pdybowski) [inline services/adminService.js]: 404

File: services/adminService.js [hunk 2]
```diff
@@ -13,46 +15,78 @@ exports.getHotelOwners = async (role) => {
...
+exports.deleteOwner = async (id, role) => {
   const user = await User.findOneAndDelete({
-    email: email,
+    _id: id,
     role: role,
   })
 
   if (!user) {
-    throw new ApiError(404, 'Wrong email or user is not a hotel owner')
+    throw new ApiError(400, 'Wrong ID or user is not a hotel owner')
```
Comment (pdybowski) [inline services/adminService.js]: 404, hotel owner with privided id not found

File: services/adminService.js [hunk 3]
```diff
@@ -13,46 +15,78 @@ exports.getHotelOwners = async (role) => {
...
-exports.deleteUser = async (email, role) => {
+exports.deleteUser = async (id, role) => {
   const user = await User.findOneAndDelete({
-    email: email,
+    _id: id,
     role: role,
   })
   if (!user) {
-    throw new ApiError(400, 'Wrong email')
+    throw new ApiError(400, 'Wrong ID')
```
Comment (pdybowski) [inline services/adminService.js]: 404, user not found

File: services/adminService.js [hunk 4]
```diff
@@ -13,46 +15,78 @@ exports.getHotelOwners = async (role) => {
...
-  const user = await User.findOneAndUpdate(
-    { _id: id },
-    { isVerified: true },
-    { useFindAndModify: false }
-  )
+exports.deleteUsers = async (users, isForceDelete) => {
+  for (const id of users) {
+    const user = await User.findById(id)
+    if (!user) {
+      throw new ApiError(400, 'User not found')
```
Comment (pdybowski) [inline services/adminService.js]: 404

File: services/adminService.js [hunk 5]
```diff
@@ -13,46 +15,78 @@ exports.getHotelOwners = async (role) => {
...
+    }
+    await User.findByIdAndDelete(id)
+  }
+}
+
+exports.deleteHotel = async (hotelId, isForceDelete) => {
+  const reservation = await Reservation.find({ hotel: hotelId })
+  const hotel = await Hotel.findById(hotelId)
+  if (!hotel) {
+    throw new ApiError(400, 'Hotel not found')
```
Comment (pdybowski) [inline services/adminService.js]: 404

File: services/adminService.js [hunk 6]
```diff
@@ -13,46 +15,78 @@ exports.getHotelOwners = async (role) => {
...
+    throw new ApiError(400, 'Remove reservation first')
+  }
+  await Hotel.findByIdAndDelete(hotelId)
+}
+
+exports.verifyUser = async (id) => {
+  const user = await User.findOneAndUpdate({ _id: id }, { isVerified: true })
   if (!user) {
-    throw new ApiError(400, "I didn't find such a user")
+    throw new ApiError(400, 'User not found')
```
Comment (pdybowski) [inline services/adminService.js]: 404

File: controllers/adminController.js [hunk 7]
```diff
@@ -28,52 +30,78 @@ exports.getHotelOwners = async (req, res, next) => {
...
+    next(new ApiError(error.statusCode, error.message))
   }
 }
 
 exports.deleteUser = async (req, res, next) => {
   try {
-    const user = await deleteUser(req.params.email, USER_ROLE)
-    res.status(200).send(user)
+    const user = await deleteUser(req.params.id, USER_ROLE)
+    res.status(200).json('Done')
```
Comment (pdybowski) [inline controllers/adminController.js]: Just sendStatus Without additonal message

File: controllers/adminController.js [hunk 8]
```diff
@@ -28,52 +30,78 @@ exports.getHotelOwners = async (req, res, next) => {
...
   } catch (error) {
     if (error instanceof mongoose.Error.CastError) {
-      return next(new ApiError(404, 'User not found'))
+      return next(new ApiError(400, 'User not found'))
```
Comment (pdybowski) [inline controllers/adminController.js]: 404

File: controllers/adminController.js [hunk 9]
```diff
@@ -28,52 +30,78 @@ exports.getHotelOwners = async (req, res, next) => {
...
+  }
+}
 
-    next(new ApiError(400, 'User data cannot be fetched'))
+exports.deleteUsers = async (req, res, next) => {
+  try {
+    const { forceDelete } = req.query
+    const isForceDelete = forceDelete === 'true'
+    const users = await deleteUsers(req.body, isForceDelete)
+    res.status(200).json('Done')
```
Comment (pdybowski) [inline controllers/adminController.js]: Just statusSend

File: controllers/adminController.js [hunk 10]
```diff
@@ -28,52 +30,78 @@ exports.getHotelOwners = async (req, res, next) => {
...
+  } catch (error) {
+    if (error instanceof mongoose.Error.CastError) {
+      return next(new ApiError(400, 'User not found'))
```
Comment (pdybowski) [inline controllers/adminController.js]: 404

File: controllers/adminController.js [hunk 11]
```diff
@@ -28,52 +30,78 @@ exports.getHotelOwners = async (req, res, next) => {
...
+
+exports.deleteHotel = async (req, res, next) => {
+  try {
+    const { forceDelete } = req.query
+    const isForceDelete = forceDelete === 'true'
+    const hotel = await deleteHotel(req.params.id, isForceDelete)
+    res.status(200).send(hotel)
+  } catch (error) {
+    if (error instanceof mongoose.Error.CastError) {
+      return next(new ApiError(400, 'Hotel not found'))
```
Comment (pdybowski) [inline controllers/adminController.js]: 404

File: controllers/adminController.js [hunk 12]
```diff
@@ -28,52 +30,78 @@ exports.getHotelOwners = async (req, res, next) => {
...
   }
 }
 
-exports.verifyOwner = async (req, res, next) => {
+exports.verifyUser = async (req, res, next) => {
   try {
-    const user = await verifyOwner(req.params.id)
-    res.sendStatus(200)
+    const user = await verifyUser(req.params.id)
+    res.status(200).json('Done')
```
Comment (pdybowski) [inline controllers/adminController.js]: Just send status

File: controllers/adminController.js [hunk 13]
```diff
@@ -28,52 +30,78 @@ exports.getHotelOwners = async (req, res, next) => {
...
   } catch (error) {
     if (error instanceof mongoose.Error.CastError) {
-      return next(new ApiError(404, 'User not found'))
+      return next(new ApiError(400, 'User not found'))
     }
```
Comment (pdybowski) [inline controllers/adminController.js:104]: 404

File: services/adminService.js (hunk 1 above)
Comment (pdybowski) [inline services/adminService.js]: 404

File: services/adminService.js (hunk 2 above)
Comment (pdybowski) [inline services/adminService.js]: 404, hotel owner with provided ID not found

File: services/adminService.js (hunk 3 above)
Comment (pdybowski) [inline services/adminService.js]: 404, user not found

File: services/adminService.js (hunk 4 above)
Comment (pdybowski) [inline services/adminService.js]: 404

File: services/adminService.js (hunk 5 above)
Comment (pdybowski) [inline services/adminService.js]: 404

File: services/adminService.js [hunk 14]
```diff
@@ -13,46 +15,78 @@ exports.getHotelOwners = async (role) => {
...
+  }
+}
+
+exports.deleteHotel = async (hotelId, isForceDelete) => {
+  const reservation = await Reservation.find({ hotel: hotelId })
+  const hotel = await Hotel.findById(hotelId)
+  if (!hotel) {
+    throw new ApiError(400, 'Hotel not found')
+  }
+  console.log(reservation)
```
Comment (pdybowski) [inline services/adminService.js]: Remove console.log

File: services/adminService.js [hunk 15]
```diff
@@ -13,46 +15,78 @@ exports.getHotelOwners = async (role) => {
...
+  if (reservation.length > 0 && isForceDelete) {
+    await Reservation.deleteMany({ hotel: hotelId })
+    await Hotel.findByIdAndDelete(hotelId)
+    //sms
+  }
+  if (reservation.length > 0 && !isForceDelete) {
+    console.log('se')
+    throw new ApiError(400, 'Remove reservation first')
```
Comment (pdybowski) [inline services/adminService.js:79]: Remove console.log

File: services/adminService.js (hunk 6 above)
Comment (pdybowski) [inline services/adminService.js]: 404

**Review by pdybowski — COMMENTED** [review]
Fix

File: controllers/adminController.js [hunk 16]
```diff
@@ -28,52 +30,78 @@ exports.getHotelOwners = async (req, res, next) => {
...
+  } catch (error) {
+    if (error instanceof mongoose.Error.CastError) {
+      return next(new ApiError(404, 'Hotel not found'))
+    }
+    next(new ApiError(error.statusCode, error.message))
   }
 }
 
-exports.verifyOwner = async (req, res, next) => {
+exports.verifyUser = async (req, res, next) => {
```
Comment (pdybowski) [inline controllers/adminController.js]: we are evryfing hotel owners, not users

File: routes/admin.js [hunk 17]
```diff
@@ -10,67 +10,28 @@ router.get('/owners', async (req, res, next) => {
...
 
-router.put('/owner/accept/:email', async (req, res, next) => {
-  adminController.acceptOwnersEmail(req, res, next)
+router.put('/owner/accept/:id', async (req, res, next) => {
+  adminController.acceptUserToOwner(req, res, next)
 })
 
 router.put('/owner/status/:id', async (req, res, next) => {
-  adminController.verifyOwner(req, res, next)
+  adminController.verifyUser(req, res, next)
```
Comment (pdybowski) [inline routes/admin.js]: should be verifyOwner, we are not veryfying normal users, 
you can add role to this function: 
image

**Review by pdybowski — COMMENTED** [review]
change function name and add role

File: services/adminService.js [hunk 18]
```diff
@@ -23,36 +25,66 @@ exports.acceptOwnersEmail = async (email, role) => {
   return user
 }
 
-exports.deleteOwner = async (email, role) => {
+exports.deleteOwner = async (id, role) => {
   const user = await User.findOneAndDelete({
-    email: email,
+    _id: id,
     role: role,
```
Comment (pdybowski) [inline services/adminService.js]: we are deleting owner so we dont need additional argument - role
we can just pass ROLE_OWNER or whatever it is named in app

File: services/adminService.js [hunk 19]
```diff
@@ -23,36 +25,66 @@ exports.acceptOwnersEmail = async (email, role) => {
...
 
   return user
 }
 
-exports.deleteUser = async (email, role) => {
+exports.deleteUser = async (id, role) => {
   const user = await User.findOneAndDelete({
-    email: email,
+    _id: id,
     role: role,
```
Comment (pdybowski) [inline services/adminService.js]: we are deleting owner so we dont need additional argument - role
we can just pass ROLE_USER or whatever it is named in app

**Review by pdybowski — COMMENTED** [review]
just set role as owner or user
