### PR TITLE
reservation routes and fixes for reservation schema

### LINKED ISSUE #10: API call - reservation
user panel:
GET all reservations for a user

POST add new reservation 
body: hotelId, roomId, startDate, endDate, adults, children, isPaid, userId

all of these need auth

### PR DESCRIPTION
**Pull request by hoolek77**

### CODE REVIEW

File: routes/reservations.js [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+    roomId: req.body.roomId,
+    startDate: req.body.startDate,
+    endDate: req.body.endDate,
+    people: {
+      adults: req.body.adults,
+      children: req.body.children,
+    },
+  })
+
+  reservation = await reservation.save()
```
Comment (pdybowski) [inline routes/reservations.js]: we dont need to assign await resevation.save() result

File: routes/reservations.js [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+
+  res.send(reservation)
+})
+
+router.put('/payment/:id', async (req, res) => {
+  const reservation = await Reservation.findByIdAndUpdate(
+    req.params.id,
+    {
+      isPaid: req.body.isPaid,
```
Comment (pdybowski) [inline routes/reservations.js]: you can actually set isPaid to true, we dont need it in body because we know that if this request comes client paid for its reservation

File: startup/routes.js [hunk 3]
```diff
@@ -17,6 +18,7 @@ module.exports = function (app) {
 
   app.use('/api', limit)
   app.use('/api/v1/users', example)
+  app.use('/api/reservations', reservations)
```
Comment (pdybowski) [inline startup/routes.js:40]: you can add v1 as you want 
api/v1/...

it says what api version we use. I guess we dont create next version so its optional - as you want

File: routes/reservations.js [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+  const { error } = validate(req.body)
+  if (error) return res.status(400).send(error.details[0].message)
+
+  let reservation = new Reservation({
+    userId: req.body.userId,
+    hotelId: req.body.hotelId,
+    roomId: req.body.roomId,
+    startDate: req.body.startDate,
+    endDate: req.body.endDate,
+    people: {
```
Comment (pdybowski) [inline routes/reservations.js:24]: hmm, is it correct with the latest schema version?

File: routes/reservations.js [hunk 5]
```diff
@@ -0,0 +1,50 @@
...
+  const reservations = await Reservation.find()
+
+  res.send(reservations)
+})
+
+router.post('/', async (req, res) => {
+  const { error } = validate(req.body)
+  if (error) return res.status(400).send(error.details[0].message)
+
+  let reservation = new Reservation({
```
Comment (pdybowski) [inline routes/reservations.js]: i think you can just pass req.body if the body is the same as reservation schema

File: routes/reservations.js [hunk 6]
```diff
@@ -0,0 +1,50 @@
...
+router.put('/payment/:id', async (req, res) => {
+  const reservation = await Reservation.findByIdAndUpdate(
+    req.params.id,
+    {
+      isPaid: true,
+    },
+    { new: true }
+  )
+
+  if (!reservation)
```
Comment (pdybowski) [inline routes/reservations.js]: we find reservation by Id and update it. then we check if there is a reservation. wrap it in try catch block and remove if statement
